name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
      - feature/askrindo
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Build with Maven
      run: mvn clean install -f transaction/pom.xml
          
    - name: Build and analyze with SonarCloud
      working-directory: transaction
      run: |
        mvn clean verify sonar:sonar \
        -Dsonar.projectKey=livindizzy_abdul-aziz \
        -Dsonar.organization=livindizzy \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
        -Dsonar.java.binaries=target/classes

    - name: Check Quality Gate
      uses: SonarSource/sonarcloud-github-action@v2.0.0
      with:
        projectKey: livindizzy_abdul-aziz
        organization: livindizzy
        wait: true
        sonar.host.url: https://sonarcloud.io
        
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
