name: CI/CD workflow for Maven Build and SonarCloud Code scan

on:
  push:
    branches:
      - main
      - feature/askrindo
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -f transaction/pom.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=livindizzy_abdul-aziz
            -Dsonar.organization=livindizzy
            -Dsonar.java.binaries=transaction/target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  quality-gate:
    name: Check SonarCloud Quality Gate
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SonarCloud Quality Gate
        uses: sonarsource/sonarcloud-quality-gate@v1.1.0
        with:
          projectKey: livindizzy_abdul-aziz
          organization: livindizzy
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
